- name: Zadanie 5.1
  hosts: vm2
#   become: yes

  tasks:

  - name: Create Folder
    file:
        path: "{{ansible_user_dir}}/kafka/"
        state: directory
    register: kafka_dir


  - name: Unarchive Apache Kafka
    unarchive:
        src: https://dlcdn.apache.org/kafka/3.2.0/kafka-3.2.0-src.tgz
        dest: "{{ kafka_dir.path }}"
        remote_src: yes

