version: '3'
services:
# имя сервиса
  nginx:
# используемый образ для первого контейнера
    image: nginx
# пробросить внутренний порт 80 наружу как 8899
    ports:
      - 8899:80
# имя сервиса
  curl:
# используемый образ для второго контейнера
    image: curlimages/curl
# после запуска второго контейнера выполнить указанный запрос к сервису первого контейнера
    command: "curl http://192.168.31.54:8899"
# второму контейнеру дождаться готовности первого
    depends_on:
      - nginx